--- #YAML:1.3
abstract: Quick design of syntax highlighted text applications
author:
  - Sebastien Grommier <sgrommier@free.fr>
distribution_type: module
licence: perl
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name: Text::Editor::Easy
version: 0.2
requires:
  IO::File: 0
  Scalar::Util: 0
  Data::Dump: 0
  Devel::Size: 0
  Thread::Queue: 0
  Time::HiRes: 0
  File::Basename: 0
  Tk: 0
  Syntax::Highlight::Perl: 0
  Fcntl: 0
  SDBM_File: 0
provides:
  Text::Editor::Easy:
    file: lib/Text/Editor/Easy.pm
    version: 0.2
  Text::Editor::Easy::Abstract:
    file: lib/Text/Editor/Easy/Abstract.pm
    version: 0.2
  Text::Editor::Easy::Comm:
    file: lib/Text/Editor/Easy/Comm.pm
    version: 0.2
  Text::Editor::Easy::Cursor:
    file: lib/Text/Editor/Easy/Cursor.pm
    version: 0.2
  Text::Editor::Easy::Data:
    file: lib/Text/Editor/Easy/Data.pm
    version: 0.2
  Text::Editor::Easy::Display:
    file: lib/Text/Editor/Easy/Display.pm
    version: 0.2
  Text::Editor::Easy::File_manager:
    file: lib/Text/Editor/Easy/File_manager.pm
    version: 0.2
  Text::Editor::Easy::Key:
    file: lib/Text/Editor/Easy/Key.pm
    version: 0.2
  Text::Editor::Easy::Line:
    file: lib/Text/Editor/Easy/Line.pm
    version: 0.2
  Text::Editor::Easy::Motion:
    file: lib/Text/Editor/Easy/Motion.pm
    version: 0.2
  Text::Editor::Easy::Graphic::Tk_glue:
    file: lib/Text/Editor/Easy/Graphic/Tk_glue.pm
    version: 0.2
  Text::Editor::Easy::Program::Flush:
    file: lib/Text/Editor/Easy/Program/Flush.pm
    version: 0.2
  Text::Editor::Easy::Program::Search:
    file: lib/Text/Editor/Easy/Program/Search.pm
    version: 0.2
  Text::Editor::Easy::Program::Tab:
    file: lib/Text/Editor/Easy/Program/Tab.pm
    version: 0.2
  Text::Editor::Easy::Program::Eval::Exec:
    file: lib/Text/Editor/Easy/Program/Eval/Exec.pm
    version: 0.2
  Text::Editor::Easy::Program::Eval::Print:
    file: lib/Text/Editor/Easy/Program/Eval/Print.pm
    version: 0.2
  Text::Editor::Easy::Program::Eval::Exec:
    file: lib/Text/Editor/Easy/Program/Eval/Exec.pm
    version: 0.2
  Text::Editor::Easy::Syntax::Perl_glue:
    file: lib/Text/Editor/Easy/Syntax/Perl_glue.pm
    version: 0.2
  Text::Editor::Easy::Trace::Print:
    file: lib/Text/Editor/Easy/Trace/Print.pm
    version: 0.2
build_requires:
  Test: 0
resources:
  homepage: http://sgrommier.free.fr/perl
generated_by: hand, Sebastien Grommier